### ISSUE TITLE
if enable auto refresh, getting issue with cowin

### ISSUE THREAD

**Issue by ghost** [sidpagariya/cowin-notifier#1]

**Comment by sidpagariya** [comment]
Hi there @newreddy thank you for opening an issue! It would be great if you could provide more information regarding what you mean by "auto refresh" and what sort of error you are seeing with the script, thanks!

**Comment by ghost** [comment]
There is auto refresh option in extension if i enabled getting below exception

Access to XMLHttpRequest at 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=294&date=23-05-2021' from origin 'https://selfregistration.cowin.gov.in' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
polyfills-es2015.15fb4198457dfa37b8c6.js:1 GET https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=294&date=23-05-2021 net::ERR_FAILED

**Comment by sidpagariya** [comment]
Hi, if you're referring to the chrome extension, my apologies but I would be unable to assist with that, but if this is something relevant to this current project, I would be more than happy to help!

**Comment by ghost** [comment]
got it. here I am not able to see captch in cmd prompt. is there any other way to see ?

**Comment by sidpagariya** [comment]
Ah okay! No worries, so if you go ahead and do a `git pull`, now you won't need to manually enter the captcha because it is now automated!! So you should be all set with captcha, and I am currently working on automating OTPs through IFTTT so instructions on that will be out soon!

**Comment by ghost** [comment]
wow, thanks let me try

**Comment by sidpagariya** [comment]
Please reopen if you run into issues, thanks!

**Comment by ghost** [comment]
getting below issue
ReferenceError: atob is not defined
src\index.ts:45:32

**Comment by sidpagariya** [comment]
Should be resolved, as per #2!

**Comment by ghost** [comment]
Thanks for quick fix. I have booked slot.
