### ISSUE TITLE
getting very frequent Error getting appointment slots

### ISSUE THREAD

**Issue by ghost** [sidpagariya/cowin-notifier#4]
getting very frequent this error is coming

Error getting appointment slots

**Comment by sidpagariya** [comment]
Looks like there might be some new updates to the API that might be causing this behavior. I have already been investigating this and haven't quite figured out why the private API requests get restricted immediately

**Comment by sandeepr365** [comment]
Yeah i see the same issue, I get this error very frequently now(every 3 minutes) and it makes impossible to get any slots booked. Thanks for your good work and it would be appreciated if you can figure out a fix for this.

**Comment by ghost** [comment]
Hi Sidpagariya,
  I think cowin site done some changes now a days , is this code can work now? looking for 2nd dose

**Comment by sidpagariya** [comment]
Hi there @newreddy sorry for the delayed response, I was travelling. The code still works since we use the public endpoint to fetch data, but the private endpoints when booking, so everything is still in order! Last I used this for my cousin was about a week back so it should still be pretty good.
